/* GÉNÉRÉ par make_pyimports.sh - ne pas modifier à la main.
   Symboles de python312.dll utilisés par le runtime C : pyhost.c définit
   pour chacun le pointeur __imp_<nom> que le code compilé lit (l'API Python
   est déclarée dllimport), et le remplit par GetProcAddress. */
#define PYHOST_IMPORTS(X) \
    X(PyBool_FromLong) \
    X(PyBool_Type) \
    X(PyBuffer_Release) \
    X(PyByteArray_Type) \
    X(PyBytes_FromObject) \
    X(PyBytes_FromStringAndSize) \
    X(PyCallable_Check) \
    X(PyConfig_Clear) \
    X(PyConfig_InitPythonConfig) \
    X(PyConfig_SetBytesString) \
    X(PyDict_GetItemString) \
    X(PyDict_New) \
    X(PyDict_SetItemString) \
    X(PyErr_Clear) \
    X(PyErr_ExceptionMatches) \
    X(PyErr_Format) \
    X(PyErr_Occurred) \
    X(PyErr_Print) \
    X(PyErr_SetNone) \
    X(PyErr_SetObject) \
    X(PyErr_SetString) \
    X(PyEval_EvalCode) \
    X(PyEval_GetBuiltins) \
    X(PyEval_RestoreThread) \
    X(PyEval_SaveThread) \
    X(PyExc_OSError) \
    X(PyExc_RuntimeError) \
    X(PyExc_SystemExit) \
    X(PyExc_TypeError) \
    X(PyExc_ValueError) \
    X(PyFloat_AsDouble) \
    X(PyFloat_FromDouble) \
    X(PyFloat_Type) \
    X(PyGILState_Ensure) \
    X(PyGILState_Release) \
    X(PyImport_AddModule) \
    X(PyImport_GetModuleDict) \
    X(PyInterpreterState_ThreadHead) \
    X(PyList_Append) \
    X(PyLong_AsLong) \
    X(PyLong_FromLong) \
    X(PyLong_FromLongLong) \
    X(PyLong_FromUnsignedLong) \
    X(PyLong_Type) \
    X(PyModule_Create2) \
    X(PyModule_GetDict) \
    X(PyModule_GetState) \
    X(PyObject_CallFunctionObjArgs) \
    X(PyObject_CallNoArgs) \
    X(PyObject_CallObject) \
    X(PyObject_GetBuffer) \
    X(PyRun_StringFlags) \
    X(PySequence_Check) \
    X(PySequence_GetItem) \
    X(PySequence_Size) \
    X(PyStatus_Exception) \
    X(PySys_GetObject) \
    X(PySys_SetObject) \
    X(PyThreadState_Get) \
    X(PyThreadState_GetInterpreter) \
    X(PyThreadState_Next) \
    X(PyThreadState_Swap) \
    X(PyTuple_New) \
    X(PyType_IsSubtype) \
    X(PyUnicode_AsUTF8AndSize) \
    X(PyUnicode_DecodeFSDefault) \
    X(PyUnicode_FromString) \
    X(PyWideStringList_Append) \
    X(Py_CompileStringExFlags) \
    X(Py_DecodeLocale) \
    X(Py_EndInterpreter) \
    X(Py_FinalizeEx) \
    X(Py_InitializeFromConfig) \
    X(Py_IsInitialized) \
    X(Py_NewInterpreterFromConfig) \
    X(_PyArg_ParseTuple_SizeT) \
    X(_PyByteArray_empty_string) \
    X(_PyObject_CallFunction_SizeT) \
    X(_Py_BuildValue_SizeT) \
    X(_Py_Dealloc) \
    X(_Py_NoneStruct) \
    /* fin */
