# Génère les icônes des grands écrans de texte (Internal.TextIcon4x32 et
# Internal.TextIcon8x32), qu'on n'écrit pas à la main : une cellule par
# caractère, chacune reconstruisant son caractère à partir de son code ASCII par
# une chaîne if/elseif dans un DynamicSelect (cf. Internal.TwoLineTextIcon pour
# la raison : une variable String n'est pas enregistrée dans les résultats).
#
#   python make_text_icons.py
#
# À relancer après toute modification de ce script (géométrie, jeu de
# caractères) ; les fichiers générés sont versionnés, comme pyimports.h.

import io
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
INTERNAL = os.path.join(ROOT, "MicroPythonMCU", "Internal")

COLS = 32            # aligné sur Interfaces.TEXT_DISPLAY_COLS
VAR = "textCode"     # tableau déclaré par Internal.PartialTextDisplay, dont l'icône hérite :
                     # les noms d'un DynamicSelect se résolvent dans la classe qui porte
                     # l'icône (déclaré par une classe sœur, omc ne le trouve pas)
PITCH_X = 6.25       # 32 colonnes sur 200 unités
PITCH_Y = 12.0
FONT_SIZE = 0        # 0 : ajustée à la cellule et suit le zoom (une taille fixe reste minuscule, quel que soit le zoom)

# Même jeu de caractères que Internal.Lcd16x2RgbIcon ; le reste s'affiche en espace.
CHARSET = " !\"#&'()*+,-./0123456789:<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"


def mo_string(c):
    return '"' + c.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fmt(x):
    return ("%.3f" % x).rstrip("0").rstrip(".")


def cell(k, x0, y0, x1, y1):
    chain = " elseif ".join(
        "abs(%s[%d] - %d) < 0.5 then %s" % (VAR, k, ord(c), mo_string(c)) for c in CHARSET)
    return ('      Text(extent = {{%s, %s}, {%s, %s}}, textString = DynamicSelect(" ", if %s else " "), '
            'textColor = {20, 60, 20}, fontName = "Courier New", fontSize = %d, textStyle = {TextStyle.Bold}),'
            % (fmt(x0), fmt(y0), fmt(x1), fmt(y1), chain, FONT_SIZE))


def icon(lines):
    half = lines * PITCH_Y / 2          # demi-hauteur de la zone de texte
    screen = half + 3                   # écran vert clair
    frame = screen + 10                 # cadre sombre
    shapes = [
        "      Rectangle(extent = {{-112, %s}, {112, -%s}}, lineColor = {0, 0, 0}, fillColor = {40, 40, 40}, fillPattern = FillPattern.Solid),"
        % (fmt(frame), fmt(frame)),
        "      Rectangle(extent = {{-102, %s}, {102, -%s}}, lineColor = {0, 0, 0}, fillColor = {190, 255, 190}, fillPattern = FillPattern.Solid),"
        % (fmt(screen), fmt(screen)),
    ]
    for i in range(lines):
        top = half - i * PITCH_Y
        for j in range(COLS):
            x0 = -100 + j * PITCH_X
            shapes.append(cell(i * COLS + j + 1, x0, top - PITCH_Y, x0 + PITCH_X, top))
    shapes.append(
        "      Rectangle(extent = {{-102, %s}, {102, -%s}}, lineColor = {120, 150, 120}, fillPattern = FillPattern.None),"
        % (fmt(screen), fmt(screen)))
    shapes.append(
        '      Text(extent = {{-150, -%s}, {150, -%s}}, textColor = {0, 0, 255}, textString = "%%name")'
        % (fmt(frame + 4), fmt(frame + 30)))
    name = "TextIcon%dx%d" % (lines, COLS)
    doc = ("<p>Base class <b>generated</b> by <code>make_text_icons.py</code> (repository root) - "
           "do not edit by hand: change the script and run it again. Icon of a %d-line, %d-column text screen: "
           "cell <code>k</code> shows the character whose ASCII code is <code>%s[k]</code>, "
           "line <code>i</code>, column <code>j</code> being <code>k = (i - 1)*%d + j</code>. "
           "It extends <code>Internal.PartialTextDisplay</code>, which declares the array and fills it: the names of a "
           "<code>DynamicSelect</code> are resolved in the class that carries the icon, so the array must be in scope here "
           "(declared by a sibling base class, it is not found and the screen stays empty in replay).</p>\n"
           "<p>Same technique as <code>Internal.TwoLineTextIcon</code> (a <code>String</code> is not stored in the results, "
           "an <code>Integer</code> is) and same tolerant comparison (<code>abs(code - N) &lt; 0.5</code>, robust to the "
           "interpolation of the replay). Character set: space, digits, letters and "
           "<code>! &quot; # &amp; &apos; ( ) * + , - . / : &lt; = &gt; ? _</code>; any other character is shown as a space.</p>"
           % (lines, COLS, VAR, COLS))
    return ("within MicroPythonMCU.Internal;\n\n"
            "partial model %s \"Icon of a %dx%d text screen (generated by make_text_icons.py): shows textCode of Internal.PartialTextDisplay, which it extends\"\n"
            "  extends Internal.PartialTextDisplay(final nLines = %d);\n"
            "  annotation(\n"
            "    Icon(coordinateSystem(preserveAspectRatio = true, extent = {{-100, -100}, {100, 100}}), graphics = {\n"
            "%s\n"
            "    }),\n"
            "    Documentation(info = \"<html>\n%s\n</html>\"));\n"
            "end %s;\n") % (name, lines, COLS, lines, "\n".join(shapes), doc, name)


def main():
    for lines in (4, 8):
        path = os.path.join(INTERNAL, "TextIcon%dx%d.mo" % (lines, COLS))
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(icon(lines))
        print("%s : %d Ko" % (os.path.relpath(path, ROOT), os.path.getsize(path) // 1024))


if __name__ == "__main__":
    main()
