within MicroPythonMCU.Interfaces;
connector DisplayLinkInput "Causal logical input of the educational display link (Peripherals.Display side) - mirror image of DisplayLinkOutput"
  input Integer seq;
  input String payload;
  input Integer charCode[DISPLAY_COLS];
  annotation(
    Icon(coordinateSystem(preserveAspectRatio = true, extent = {{-100, -100}, {100, 100}}), graphics = {Polygon(points = {{-100, 50}, {0, 0}, {-100, -50}, {-100, 50}}, lineColor = {28, 108, 200}, fillColor = {28, 108, 200}, fillPattern = FillPattern.Solid)}),
    Documentation(info = "<html>
<p>Causal connector (input) of the educational display link, to be wired with <code>connect()</code> to a <code>DisplayLinkOutput</code> (e.g. <code>connect(mcu.Display0, display.displayLink)</code>). No default value on the fields themselves (an unconditional default would conflict with the equation generated by <code>connect()</code>, a pitfall already met and documented in <code>requirements.md</code> - <code>Error: Too many equations, over-determined system</code>): this connector is meant to always be connected when <code>Peripherals.Display</code> is used in a schematic. See <code>DisplayLinkOutput</code> and the decision \"Périphérique d'affichage pédagogique\" in <code>requirements.md</code>.</p>
</html>"));
end DisplayLinkInput;
